import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Pricing App",
    description: "Generated by create next app",
};

export default function PricingPage(){
    return(
        <>
        <span>Pricing Page</span>
        </>
    )
}