import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About App",
    description: "Generated by create next app",
};

export default function AboutPage(){
    return(

        <span className="text-7xl" >About Page</span>
    )
}