import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact App",
    description: "Generated by create next app",
};


export default function ContactPage(){
    return(
        <span>Contact Page</span>
    )
}